"""Tests for the CDDIS GIM adapter.

The unit tests exercise:

* The IONEX parser against a synthetic fixture committed under
  ``tests/fixtures/cddis_gim/``. The fixture is regenerated by
  ``tests/fixtures/cddis_gim/_generate_synthetic.py`` so reviewers can
  audit the assumed analytic TEC distribution.
* The Earthdata authentication flow (env-var detection, missing-credentials
  error, ``earthaccess`` opt-in, manual httpx fallback).
* The download routing (legacy ``.Z`` vs long-form ``.gz`` filename
  conventions), with mocked httpx responses.
* The unified streaming :meth:`fetch_tec_maps` and the bilinear-point
  :meth:`fetch_tec_at_point` paths, end-to-end against the synthetic
  fixture as if it were the live CDDIS response.

The *critical* assertion is the Gannon-storm smoke test: a
``fetch_tec_at_point(lat=40.0, lon=-83.0)`` call across the May 10-11
2024 window yields TEC > 30 TECU at the storm-peak epoch. With the
synthetic fixture this asserts the parser + bilinear-interp + diurnal
modelling are all wired correctly; the same test is also marked
``@pytest.mark.live`` with the real CDDIS URL for nightly runs.
"""

from __future__ import annotations

import gzip
import os
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import httpx
import pytest

from helios_connectors import CddisGimAdapter, SourceID
from helios_connectors.adapters.cddis_gim import (
    CDDIS_BASE_URL,
    CDDIS_DEFAULT_CENTER,
    CDDIS_SUPPORTED_CENTERS,
    IonexFile,
    IonexMap,
    _bilinear_sample,
    _bracket,
    _candidate_urls,
    _decompress_ionex,
    _decompress_unix_z,
    _EarthaccessUnavailable,
    _ensure_utc,
    _finalize_row,
    _isnan,
    parse_ionex,
)

FIXTURES = Path(__file__).parent / "fixtures" / "cddis_gim"
SYNTHETIC_PLAIN = FIXTURES / "synthetic_gannon_2024131.inx"
SYNTHETIC_GZ = FIXTURES / "synthetic_gannon_2024131.inx.gz"

GANNON_DAY_START = datetime(2024, 5, 10, 0, 0, 0, tzinfo=UTC)
GANNON_DAY_END = datetime(2024, 5, 11, 0, 0, 0, tzinfo=UTC)


# ---------------------------------------------------------------------------- #
# Pure helper tests
# ---------------------------------------------------------------------------- #


def test_ensure_utc_passes_through_aware() -> None:
    ts = datetime(2024, 5, 10, 12, tzinfo=UTC)
    assert _ensure_utc(ts) is ts


def test_ensure_utc_treats_naive_as_utc() -> None:
    naive = datetime(2024, 5, 10, 12)
    out = _ensure_utc(naive)
    assert out.tzinfo is UTC


def test_isnan_helper() -> None:
    assert _isnan(float("nan")) is True
    assert _isnan(0.0) is False
    assert _isnan(42.0) is False


def test_bracket_ascending_inside() -> None:
    axis = (0.0, 1.0, 2.0, 3.0)
    i0, i1, f = _bracket(1.5, axis)
    assert (i0, i1) == (1, 2)
    assert f == pytest.approx(0.5)


def test_bracket_ascending_clamp_left() -> None:
    assert _bracket(-5.0, (0.0, 1.0, 2.0)) == (0, 0, 0.0)


def test_bracket_ascending_clamp_right() -> None:
    axis = (0.0, 1.0, 2.0)
    i0, i1, f = _bracket(99.0, axis)
    assert (i0, i1, f) == (2, 2, 0.0)


def test_bracket_descending_inside() -> None:
    axis = (90.0, 80.0, 70.0)
    i0, i1, f = _bracket(85.0, axis)
    assert (i0, i1) == (0, 1)
    assert f == pytest.approx(0.5)


def test_bracket_descending_clamp() -> None:
    axis = (90.0, 80.0, 70.0)
    assert _bracket(95.0, axis) == (0, 0, 0.0)
    assert _bracket(60.0, axis) == (2, 2, 0.0)


def test_bracket_singleton_axis() -> None:
    assert _bracket(5.0, (42.0,)) == (0, 0, 0.0)


def test_bracket_empty_axis_raises() -> None:
    with pytest.raises(ValueError):
        _bracket(0.0, ())


def test_finalize_row_pads_short_input() -> None:
    row = _finalize_row([10, 20, 30], n_lon=5, scale=0.1)
    assert len(row) == 5
    assert row[0] == pytest.approx(1.0)
    # padded with sentinels → NaN
    assert _isnan(row[3])
    assert _isnan(row[4])


def test_finalize_row_sentinel_becomes_nan() -> None:
    row = _finalize_row([100, 9999, 50], n_lon=3, scale=0.1)
    assert row[0] == pytest.approx(10.0)
    assert _isnan(row[1])
    assert row[2] == pytest.approx(5.0)


# ---------------------------------------------------------------------------- #
# Candidate-URL probe order
# ---------------------------------------------------------------------------- #


def test_candidate_urls_pre_long_form_year_prefers_legacy() -> None:
    urls = _candidate_urls(year=2018, doy=100, center="igsg")
    assert "igsg1000.18i.Z" in urls[0]
    assert "OPSFIN" in urls[1]


def test_candidate_urls_post_long_form_year_prefers_long_form() -> None:
    urls = _candidate_urls(year=2024, doy=131, center="igsg")
    assert "IGS0OPSFIN" in urls[0]
    assert "igsg1310.24i.Z" in urls[1]


def test_candidate_urls_jpl_center() -> None:
    urls = _candidate_urls(year=2024, doy=131, center="jplg")
    assert "JPL0OPSFIN" in urls[0]


# ---------------------------------------------------------------------------- #
# Decompression
# ---------------------------------------------------------------------------- #


def test_decompress_gz() -> None:
    payload = b"plain IONEX text\n"
    gz = gzip.compress(payload)
    assert _decompress_ionex(gz, "foo.inx.gz") == payload


def test_decompress_plain_passthrough() -> None:
    payload = b"plain IONEX text\n"
    assert _decompress_ionex(payload, "foo.inx") == payload


def test_decompress_z_rejects_bad_magic() -> None:
    with pytest.raises(ValueError, match=r"not a \.Z"):
        _decompress_unix_z(b"not-a-Z-file")


def test_decompress_z_without_unlzw3_raises_runtime_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If a user requests a pre-2023 .Z file without the [earthdata] extra
    installed, we raise a clear actionable RuntimeError pointing them at
    the right pip install."""

    # Force ``import unlzw3`` to fail inside _decompress_unix_z.
    import builtins

    real_import = builtins.__import__

    def fake_import(name: str, *a: Any, **kw: Any) -> Any:
        if name == "unlzw3":
            raise ImportError("forced for test")
        return real_import(name, *a, **kw)

    monkeypatch.setattr(builtins, "__import__", fake_import)
    # Magic header is correct so we fall through to the import.
    fake_z = b"\x1f\x9d\x90"
    with pytest.raises(RuntimeError, match="unlzw3"):
        _decompress_unix_z(fake_z)


def test_decompress_dispatch_on_extension() -> None:
    """``_decompress_ionex`` routes by suffix: .gz, .Z, or passthrough."""

    payload = b"plain text"
    # .GZ (uppercase) should also be detected (defensive).
    gz = gzip.compress(payload)
    assert _decompress_ionex(gz, "FOO.INX.GZ") == payload


# ---------------------------------------------------------------------------- #
# IONEX parser against the synthetic fixture
# ---------------------------------------------------------------------------- #


@pytest.fixture(scope="session")
def synthetic_ionex_text() -> bytes:
    return SYNTHETIC_PLAIN.read_bytes()


@pytest.fixture(scope="session")
def synthetic_ionex(synthetic_ionex_text: bytes) -> IonexFile:
    return parse_ionex(synthetic_ionex_text, source_url=str(SYNTHETIC_PLAIN))


def test_parse_ionex_header_fields(synthetic_ionex: IonexFile) -> None:
    assert synthetic_ionex.epoch_first == datetime(2024, 5, 10, 0, 0, 0, tzinfo=UTC)
    assert synthetic_ionex.epoch_last == datetime(2024, 5, 11, 0, 0, 0, tzinfo=UTC)
    assert synthetic_ionex.interval_seconds == 7200
    assert synthetic_ionex.lat1 == 87.5
    assert synthetic_ionex.lat2 == -87.5
    assert synthetic_ionex.dlat == -2.5
    assert synthetic_ionex.lon1 == -180.0
    assert synthetic_ionex.lon2 == 180.0
    assert synthetic_ionex.dlon == 5.0
    assert synthetic_ionex.exponent == -1


def test_parse_ionex_has_13_maps(synthetic_ionex: IonexFile) -> None:
    assert len(synthetic_ionex.maps) == 13


def test_parse_ionex_grid_dims(synthetic_ionex: IonexFile) -> None:
    m = synthetic_ionex.maps[0]
    assert len(m.tec_grid) == 71  # latitudes
    assert len(m.tec_grid[0]) == 73  # longitudes


def test_parse_ionex_lat_axis(synthetic_ionex: IonexFile) -> None:
    axis = synthetic_ionex.lat_axis()
    assert axis[0] == 87.5
    assert axis[-1] == -87.5
    assert len(axis) == 71


def test_parse_ionex_lon_axis(synthetic_ionex: IonexFile) -> None:
    axis = synthetic_ionex.lon_axis()
    assert axis[0] == -180.0
    assert axis[-1] == 180.0
    assert len(axis) == 73


def test_parse_ionex_epochs_2h_apart(synthetic_ionex: IonexFile) -> None:
    deltas = [
        (synthetic_ionex.maps[i + 1].epoch - synthetic_ionex.maps[i].epoch)
        for i in range(len(synthetic_ionex.maps) - 1)
    ]
    assert all(d == timedelta(hours=2) for d in deltas)


def test_parse_ionex_height_recorded(synthetic_ionex: IonexFile) -> None:
    assert all(m.height_km == 450.0 for m in synthetic_ionex.maps)


def test_parse_ionex_rejects_missing_header() -> None:
    with pytest.raises(ValueError, match="END OF HEADER"):
        parse_ionex(b"no header here\nsome data\n")


def test_parse_ionex_rejects_missing_epoch_records() -> None:
    bad = b"                                                            END OF HEADER\n"
    with pytest.raises(ValueError, match="EPOCH OF FIRST/LAST"):
        parse_ionex(bad)


def test_parse_ionex_accepts_bytes_or_str(synthetic_ionex_text: bytes) -> None:
    a = parse_ionex(synthetic_ionex_text)
    b = parse_ionex(synthetic_ionex_text.decode("ascii"))
    assert len(a.maps) == len(b.maps) == 13


# ---------------------------------------------------------------------------- #
# Bilinear sampler
# ---------------------------------------------------------------------------- #


def test_bilinear_sample_columbus_gannon_peak(synthetic_ionex: IonexFile) -> None:
    """The synthetic Gannon-bump should peak around (40N, -83W) at 20 UT."""

    map_20 = next(m for m in synthetic_ionex.maps if m.epoch.hour == 20)
    tec = _bilinear_sample(synthetic_ionex, map_20, 40.0, -83.0)
    assert tec > 30.0, f"expected Gannon enhancement at (40, -83); got {tec:.1f} TECU"


def test_bilinear_sample_remote_quiet(synthetic_ionex: IonexFile) -> None:
    """Far from the Gannon centre + nighttime → low TEC."""

    map_quiet = next(m for m in synthetic_ionex.maps if m.epoch.hour == 4)
    tec = _bilinear_sample(synthetic_ionex, map_quiet, -60.0, 150.0)
    assert 0.0 <= tec < 25.0


def test_bilinear_sample_on_grid_point(synthetic_ionex: IonexFile) -> None:
    """Sampling exactly on a grid point should return that cell's value."""

    map0 = synthetic_ionex.maps[0]
    # Lat axis is 87.5, 85.0, 82.5, ...; pick (87.5, -180.0)
    on_grid = _bilinear_sample(synthetic_ionex, map0, 87.5, -180.0)
    expected = map0.tec_grid[0][0]
    assert on_grid == pytest.approx(expected, rel=1e-6)


def test_bilinear_sample_nan_falls_back_to_mean() -> None:
    """If some corners are NaN, sampler returns the mean of valid corners."""

    nan = float("nan")
    ionex = IonexFile(
        epoch_first=GANNON_DAY_START,
        epoch_last=GANNON_DAY_START,
        interval_seconds=7200,
        lat1=10.0,
        lat2=0.0,
        dlat=-10.0,
        lon1=0.0,
        lon2=10.0,
        dlon=10.0,
        exponent=-1,
        maps=(),
    )
    grid = ((nan, 4.0), (10.0, 20.0))
    m = IonexMap(epoch=GANNON_DAY_START, tec_grid=grid, height_km=450.0)
    val = _bilinear_sample(ionex, m, 5.0, 5.0)
    # (4 + 10 + 20) / 3 = 11.33...
    assert val == pytest.approx((4.0 + 10.0 + 20.0) / 3.0)


def test_bilinear_sample_all_nan_returns_nan() -> None:
    nan = float("nan")
    ionex = IonexFile(
        epoch_first=GANNON_DAY_START,
        epoch_last=GANNON_DAY_START,
        interval_seconds=7200,
        lat1=10.0,
        lat2=0.0,
        dlat=-10.0,
        lon1=0.0,
        lon2=10.0,
        dlon=10.0,
        exponent=-1,
        maps=(),
    )
    grid = ((nan, nan), (nan, nan))
    m = IonexMap(epoch=GANNON_DAY_START, tec_grid=grid, height_km=450.0)
    assert _isnan(_bilinear_sample(ionex, m, 5.0, 5.0))


# ---------------------------------------------------------------------------- #
# Adapter — credential handling
# ---------------------------------------------------------------------------- #


@pytest.fixture
def _no_earthdata_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("NASA_EARTHDATA_USER", raising=False)
    monkeypatch.delenv("NASA_EARTHDATA_PASS", raising=False)


@pytest.fixture
def _stub_earthdata_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("NASA_EARTHDATA_USER", "stub-user")
    monkeypatch.setenv("NASA_EARTHDATA_PASS", "stub-pass")


@pytest.mark.asyncio
async def test_missing_credentials_raises_clear_error(
    _no_earthdata_env: None, tmp_path: Path
) -> None:
    adapter = CddisGimAdapter(
        cache=False,
        cache_root=tmp_path,
        use_earthaccess=False,
    )
    try:
        with pytest.raises(RuntimeError, match="NASA_EARTHDATA_USER"):
            await adapter._ensure_authenticated()
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_credentials_from_env_var_pickup(_stub_earthdata_env: None, tmp_path: Path) -> None:
    adapter = CddisGimAdapter(
        cache=False,
        cache_root=tmp_path,
        use_earthaccess=False,
    )
    try:
        await adapter._ensure_authenticated()
        assert adapter._urs_authenticated is True
        # Manual path sets Basic auth on the httpx client.
        assert adapter._client.auth is not None
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_earthaccess_required_but_missing_raises(
    _stub_earthdata_env: None, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Force the earthaccess loader to report unavailable.
    from helios_connectors.adapters import cddis_gim

    def _raise(*_a: Any, **_kw: Any) -> Any:
        raise _EarthaccessUnavailable()

    monkeypatch.setattr(cddis_gim, "_build_earthaccess_session", _raise)
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=True)
    try:
        with pytest.raises(RuntimeError, match="earthaccess"):
            await adapter._ensure_authenticated()
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_invalid_center_rejected(_stub_earthdata_env: None, tmp_path: Path) -> None:
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path)
    try:
        with pytest.raises(ValueError, match="unsupported analysis center"):
            adapter._validate_center("bogus")
    finally:
        await adapter.aclose()


def test_supported_centers_table_has_expected_keys() -> None:
    assert set(CDDIS_SUPPORTED_CENTERS) == {"igsg", "jplg", "codg", "esag", "upcg"}
    assert CDDIS_DEFAULT_CENTER == "igsg"


# ---------------------------------------------------------------------------- #
# Adapter — end-to-end via injected cache (no live HTTP)
# ---------------------------------------------------------------------------- #


def _seed_cache(cache_root: Path, year: int, doy: int, center: str) -> None:
    """Plant the synthetic IONEX in the adapter's raw cache so the
    download path is bypassed entirely (cache hit on first lookup)."""

    day_dir = cache_root / f"{year:04d}" / f"{doy:03d}"
    day_dir.mkdir(parents=True, exist_ok=True)
    target = day_dir / f"{center}_{year:04d}_{doy:03d}.ionex"
    target.write_bytes(SYNTHETIC_PLAIN.read_bytes())


@pytest.mark.asyncio
async def test_fetch_tec_maps_yields_per_2h_records(
    _stub_earthdata_env: None, tmp_path: Path
) -> None:
    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        records: list[Any] = []
        async for rec in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END):
            records.append(rec)
        assert len(records) == 13  # 00, 02, 04, ..., 24 UTC
        # Every record carries the expected provenance shape.
        assert all(rec.source == SourceID.CDDIS_GIM for rec in records)
        assert all(rec.record_type == "tec_map" for rec in records)
        assert all(rec.value_units == "TECU" for rec in records)
        # Grid dimensions
        first_grid = records[0].value["tec_grid"]
        assert len(first_grid) == 71
        assert len(first_grid[0]) == 73
        # Lineage cites the analysis-center name
        assert records[0].provenance.extra is not None
        assert "IGS combined" in records[0].provenance.extra["lineage"]
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_tec_at_point_gannon_storm_elevated(
    _stub_earthdata_env: None, tmp_path: Path
) -> None:
    """The headline regression test: TEC at Columbus, OH spikes above
    30 TECU during the Gannon storm peak."""

    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        records: list[Any] = []
        async for rec in adapter.fetch_tec_at_point(
            start=GANNON_DAY_START,
            end=GANNON_DAY_END,
            lat=40.0,
            lon=-83.0,
        ):
            records.append(rec)
        # All 13 epochs covered.
        assert len(records) == 13
        # Peak TEC during the storm-amplified window (around 20 UT) must
        # exceed 30 TECU — matches the published Gannon-storm enhancement
        # (>50 TECU) over the U.S. Midwest, and the synthetic fixture's
        # built-in Gaussian bump that mimics it.
        peak_tec = max(rec.value["tec"] for rec in records)
        assert peak_tec > 30.0, f"expected peak > 30 TECU; got {peak_tec:.1f}"
        # Peak should be at or near 20 UT.
        peak_record = max(records, key=lambda r: r.value["tec"])
        assert 18 <= peak_record.event_time.hour <= 22
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_unified_dispatches_to_tec_maps(
    _stub_earthdata_env: None, tmp_path: Path
) -> None:
    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        records = [rec async for rec in adapter.fetch(start=GANNON_DAY_START, end=GANNON_DAY_END)]
        assert len(records) == 13
        assert records[0].record_type == "tec_map"
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_rejects_unknown_product(_stub_earthdata_env: None, tmp_path: Path) -> None:
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path)
    try:
        with pytest.raises(ValueError, match="unknown CDDIS GIM products"):
            async for _ in adapter.fetch(
                start=GANNON_DAY_START,
                end=GANNON_DAY_END,
                products=["nonsense"],
            ):
                pass
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_rejects_end_before_start(_stub_earthdata_env: None, tmp_path: Path) -> None:
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path)
    try:
        with pytest.raises(ValueError, match="precedes start"):
            async for _ in adapter.fetch_tec_maps(start=GANNON_DAY_END, end=GANNON_DAY_START):
                pass
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_tec_at_point_rejects_bad_lat(
    _stub_earthdata_env: None, tmp_path: Path
) -> None:
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path)
    try:
        with pytest.raises(ValueError, match="lat out of range"):
            async for _ in adapter.fetch_tec_at_point(
                start=GANNON_DAY_START,
                end=GANNON_DAY_END,
                lat=99.0,
                lon=0.0,
            ):
                pass
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_fetch_tec_at_point_wraps_longitude(
    _stub_earthdata_env: None, tmp_path: Path
) -> None:
    """A user might pass lon in ``[0, 360]``; the adapter wraps to ``[-180, +180]``."""

    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        # -83 east is also 277 east.
        recs_a = [
            r
            async for r in adapter.fetch_tec_at_point(
                start=GANNON_DAY_START, end=GANNON_DAY_END, lat=40.0, lon=-83.0
            )
        ]
        recs_b = [
            r
            async for r in adapter.fetch_tec_at_point(
                start=GANNON_DAY_START, end=GANNON_DAY_END, lat=40.0, lon=277.0
            )
        ]
        assert len(recs_a) == len(recs_b) == 13
        for a, b in zip(recs_a, recs_b, strict=True):
            assert a.value["tec"] == pytest.approx(b.value["tec"], rel=1e-6)
    finally:
        await adapter.aclose()


# ---------------------------------------------------------------------------- #
# Adapter — download path with mocked transport
# ---------------------------------------------------------------------------- #


def _mock_transport_404_then_synthetic() -> httpx.MockTransport:
    """First request → 404 (legacy short-form miss); second request →
    200 with the synthetic IONEX gzipped (long-form hit)."""

    synthetic_gz = gzip.compress(SYNTHETIC_PLAIN.read_bytes())
    calls: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(str(request.url))
        if request.url.path.endswith(".Z"):
            return httpx.Response(404)
        return httpx.Response(
            200,
            content=synthetic_gz,
            headers={"content-type": "application/octet-stream"},
        )

    transport = httpx.MockTransport(handler)
    transport._calls = calls  # type: ignore[attr-defined]
    return transport


@pytest.mark.asyncio
async def test_download_path_falls_back_on_404(_stub_earthdata_env: None, tmp_path: Path) -> None:
    transport = _mock_transport_404_then_synthetic()
    client = httpx.AsyncClient(transport=transport, base_url=CDDIS_BASE_URL)
    adapter = CddisGimAdapter(
        client=client, cache=False, cache_root=tmp_path, use_earthaccess=False
    )
    try:
        records = [
            rec async for rec in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END)
        ]
        assert len(records) == 13
        # Both the long-form .gz (200) and the legacy .Z (404) URLs were tried.
        calls = transport._calls  # type: ignore[attr-defined]
        assert any(".gz" in c for c in calls)
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_download_html_payload_raises(_stub_earthdata_env: None, tmp_path: Path) -> None:
    """Hitting the URS login page (HTML body) is a configuration error,
    not a 200 to silently propagate."""

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            content=b"<html>URS login page</html>",
            headers={"content-type": "text/html; charset=utf-8"},
        )

    transport = httpx.MockTransport(handler)
    client = httpx.AsyncClient(transport=transport, base_url=CDDIS_BASE_URL)
    adapter = CddisGimAdapter(
        client=client, cache=False, cache_root=tmp_path, use_earthaccess=False
    )
    try:
        with pytest.raises(RuntimeError, match="URS login page"):
            async for _ in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END):
                pass
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_download_double_404_yields_no_records(
    _stub_earthdata_env: None, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Every candidate URL returns 404 → adapter logs a warning and the
    iterator yields nothing for that day."""

    def handler(_request: httpx.Request) -> httpx.Response:
        return httpx.Response(404)

    transport = httpx.MockTransport(handler)
    client = httpx.AsyncClient(transport=transport, base_url=CDDIS_BASE_URL)
    adapter = CddisGimAdapter(
        client=client, cache=False, cache_root=tmp_path, use_earthaccess=False
    )
    try:
        records = [
            rec
            async for rec in adapter.fetch_tec_maps(
                start=GANNON_DAY_START, end=GANNON_DAY_START + timedelta(hours=23)
            )
        ]
        assert records == []
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_cache_round_trip(_stub_earthdata_env: None, tmp_path: Path) -> None:
    """The first request populates the cache; the second is a pure
    cache hit and does not touch the (404-only) mock transport."""

    transport = _mock_transport_404_then_synthetic()
    client = httpx.AsyncClient(transport=transport, base_url=CDDIS_BASE_URL)
    adapter = CddisGimAdapter(
        client=client, cache=False, cache_root=tmp_path, use_earthaccess=False
    )
    try:
        # First pass: populates cache.
        recs1 = [
            r async for r in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END)
        ]
        first_call_count = len(transport._calls)  # type: ignore[attr-defined]
        # Second pass: same window, should be a pure cache hit.
        recs2 = [
            r async for r in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END)
        ]
        second_call_count = len(transport._calls)  # type: ignore[attr-defined]
        assert len(recs1) == len(recs2) == 13
        assert second_call_count == first_call_count, "expected no new HTTP calls"
    finally:
        await adapter.aclose()


# ---------------------------------------------------------------------------- #
# Provenance-spec compliance — adapter records ARE HeliosModelOutputRecord
# ---------------------------------------------------------------------------- #


@pytest.mark.asyncio
async def test_point_record_is_spec_compliant(_stub_earthdata_env: None, tmp_path: Path) -> None:
    """tec_point records carry a scalar TEC value on the provenance record."""

    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        rec = None
        async for r in adapter.fetch_tec_at_point(
            start=GANNON_DAY_START, end=GANNON_DAY_END, lat=40.0, lon=-83.0
        ):
            rec = r
            break
        assert rec is not None
        prov = rec.provenance
        assert prov.value_units == "TECU"
        assert isinstance(prov.value, (int, float))
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_map_record_carries_grid_in_extra(_stub_earthdata_env: None, tmp_path: Path) -> None:
    """tec_map records put the full grid in extra and use the spatial-mean
    TEC as the scalar value on the provenance record."""

    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    try:
        rec = None
        async for r in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END):
            rec = r
            break
        assert rec is not None
        prov = rec.provenance
        assert prov.extra is not None
        assert prov.extra["tec_grid_shape"] == [71, 73]
        assert isinstance(prov.value, (int, float))
    finally:
        await adapter.aclose()


# ---------------------------------------------------------------------------- #
# Live integration test — deselected by default
# ---------------------------------------------------------------------------- #


@pytest.mark.asyncio
async def test_earthaccess_path_authenticates_and_downloads(
    _stub_earthdata_env: None, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When ``earthaccess`` is "available" (stubbed), the adapter routes
    downloads through its ``requests`` session — verified via a fake
    session that returns our synthetic gzipped IONEX."""

    from helios_connectors.adapters import cddis_gim as cddis_mod

    class FakeSession:
        def __init__(self) -> None:
            self.calls: list[str] = []

        def get(self, url: str, **_kw: Any) -> Any:
            self.calls.append(url)
            payload = gzip.compress(SYNTHETIC_PLAIN.read_bytes())

            class _Resp:
                status_code = 200
                content = payload

                def raise_for_status(self) -> None:
                    pass

            return _Resp()

    fake_session = FakeSession()

    def fake_build_session(user: str, password: str) -> Any:
        assert user == "stub-user"
        assert password == "stub-pass"
        return fake_session

    monkeypatch.setattr(cddis_mod, "_build_earthaccess_session", fake_build_session)

    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=True)
    try:
        records = [
            r async for r in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END)
        ]
        assert len(records) == 13
        assert fake_session.calls, "earthaccess session should have been called"
        assert adapter._earthaccess_session is fake_session
    finally:
        await adapter.aclose()


@pytest.mark.asyncio
async def test_earthaccess_404_falls_through_to_next_candidate(
    _stub_earthdata_env: None, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When the earthaccess session reports 404, the candidate-URL probe
    advances to the next URL transparently."""

    from helios_connectors.adapters import cddis_gim as cddis_mod

    class FakeSession:
        def __init__(self) -> None:
            self.calls: list[str] = []

        def get(self, url: str, **_kw: Any) -> Any:
            self.calls.append(url)
            if url.endswith(".Z"):

                class _R404:
                    status_code = 404
                    content = b""

                    def raise_for_status(self) -> None:
                        raise httpx.HTTPStatusError(
                            "404",
                            request=None,
                            response=None,  # type: ignore[arg-type]
                        )

                return _R404()
            payload = gzip.compress(SYNTHETIC_PLAIN.read_bytes())

            class _OK:
                status_code = 200
                content = payload

                def raise_for_status(self) -> None:
                    pass

            return _OK()

    fake_session = FakeSession()

    monkeypatch.setattr(
        cddis_mod,
        "_build_earthaccess_session",
        lambda *_a, **_kw: fake_session,
    )

    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=True)
    try:
        records = [
            r async for r in adapter.fetch_tec_maps(start=GANNON_DAY_START, end=GANNON_DAY_END)
        ]
        assert len(records) == 13
    finally:
        await adapter.aclose()


def test_fetch_sync_wrapper(_stub_earthdata_env: None, tmp_path: Path) -> None:
    """``fetch_sync`` (inherited from BaseAdapter) drains the async stream
    into a list for notebook users."""

    _seed_cache(tmp_path, 2024, 131, "igsg")
    adapter = CddisGimAdapter(cache=False, cache_root=tmp_path, use_earthaccess=False)
    records = adapter.fetch_sync(start=GANNON_DAY_START, end=GANNON_DAY_END)
    assert len(records) == 13
    assert all(r.source == SourceID.CDDIS_GIM for r in records)


def test_parse_ionex_skips_rms_block() -> None:
    """IONEX files often interleave RMS maps after each TEC map. The
    parser must skip RMS blocks while still capturing every TEC map."""

    lines = []

    def emit(body: str, label: str) -> None:
        lines.append(body.ljust(60)[:60] + label)

    # Minimal header
    emit("    1.0           I", "IONEX VERSION / TYPE")
    emit("  2024     5    10     0     0     0", "EPOCH OF FIRST MAP")
    emit("  2024     5    10     0     0     0", "EPOCH OF LAST MAP")
    emit("  7200", "INTERVAL")
    emit("     1", "# OF MAPS IN FILE")
    emit("    10.0    -10.0    -10.0", "LAT1 / LAT2 / DLAT")
    emit("     0.0     10.0     10.0", "LON1 / LON2 / DLON")
    emit("    -1", "EXPONENT")
    emit("", "END OF HEADER")
    # Map 1: a 3x2 grid (lat 10, 0, -10; lon 0, 10)
    emit("     1", "START OF TEC MAP")
    emit("  2024     5    10     0     0     0", "EPOCH OF CURRENT MAP")
    emit("    10.0      0.0     10.0     10.0    450.0", "LAT/LON1/LON2/DLON/H")
    lines.append("  100  200")
    emit("     0.0      0.0     10.0     10.0    450.0", "LAT/LON1/LON2/DLON/H")
    lines.append("  150  250")
    emit("   -10.0      0.0     10.0     10.0    450.0", "LAT/LON1/LON2/DLON/H")
    lines.append("  120  180")
    emit("     1", "END OF TEC MAP")
    # RMS block — should be silently skipped.
    emit("     1", "START OF RMS MAP")
    lines.append("rms junk that the parser must skip")
    emit("     1", "END OF RMS MAP")
    emit("", "END OF FILE")

    text = "\n".join(lines) + "\n"
    ionex = parse_ionex(text.encode())
    assert len(ionex.maps) == 1
    assert ionex.maps[0].tec_grid[0][0] == pytest.approx(10.0)  # 100 * 10**-1
    assert ionex.maps[0].tec_grid[1][1] == pytest.approx(25.0)


def test_parse_ionex_default_interval_when_missing() -> None:
    """If the IONEX header omits INTERVAL the parser defaults to 7200s."""

    lines = []

    def emit(body: str, label: str) -> None:
        lines.append(body.ljust(60)[:60] + label)

    emit("    1.0           I", "IONEX VERSION / TYPE")
    emit("  2024     5    10     0     0     0", "EPOCH OF FIRST MAP")
    emit("  2024     5    10     2     0     0", "EPOCH OF LAST MAP")
    # (no INTERVAL record)
    emit("     1", "# OF MAPS IN FILE")
    emit("    10.0      0.0    -10.0", "LAT1 / LAT2 / DLAT")
    emit("     0.0     10.0     10.0", "LON1 / LON2 / DLON")
    emit("    -1", "EXPONENT")
    emit("", "END OF HEADER")
    emit("     1", "START OF TEC MAP")
    emit("  2024     5    10     0     0     0", "EPOCH OF CURRENT MAP")
    emit("    10.0      0.0     10.0     10.0    450.0", "LAT/LON1/LON2/DLON/H")
    lines.append("    1    2")
    emit("     0.0      0.0     10.0     10.0    450.0", "LAT/LON1/LON2/DLON/H")
    lines.append("    3    4")
    emit("     1", "END OF TEC MAP")
    emit("", "END OF FILE")

    ionex = parse_ionex("\n".join(lines).encode())
    assert ionex.interval_seconds == 7200


def test_parse_ionex_rejects_missing_grid_spec() -> None:
    """A header without LAT/LON grid records is unrecoverable."""

    lines = []

    def emit(body: str, label: str) -> None:
        lines.append(body.ljust(60)[:60] + label)

    emit("    1.0           I", "IONEX VERSION / TYPE")
    emit("  2024     5    10     0     0     0", "EPOCH OF FIRST MAP")
    emit("  2024     5    10     0     0     0", "EPOCH OF LAST MAP")
    emit("", "END OF HEADER")

    with pytest.raises(ValueError, match="LAT/LON grid spec"):
        parse_ionex("\n".join(lines).encode())


@pytest.mark.live
@pytest.mark.asyncio
async def test_live_cddis_columbus_gannon(tmp_path: Path) -> None:
    """Hits live CDDIS for the real Gannon-storm peak day.

    Skipped unless ``NASA_EARTHDATA_USER``/``NASA_EARTHDATA_PASS`` are
    set. Run with ``pytest -m live`` after exporting credentials.
    """

    if not (os.environ.get("NASA_EARTHDATA_USER") and os.environ.get("NASA_EARTHDATA_PASS")):
        pytest.skip("NASA_EARTHDATA_USER/PASS not set")

    async with CddisGimAdapter(cache_root=tmp_path) as adapter:
        records = [
            r
            async for r in adapter.fetch_tec_at_point(
                start=GANNON_DAY_START,
                end=GANNON_DAY_END,
                lat=40.0,
                lon=-83.0,
            )
        ]
    assert len(records) >= 12
    peak = max(r.value["tec"] for r in records)
    # Real Gannon TEC peaked > 50 TECU over the U.S. Midwest; assert > 30
    # as the kill-gate-friendly lower bound that won't flake on small
    # analysis-center variation.
    assert peak > 30.0, f"expected real Gannon-week TEC > 30 TECU; got {peak:.1f}"
